### ISSUE TITLE
jinja2 recognizing tex commands as variables

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/template-mit-demo#5]
sort of an off-shoot of #2, stack trace from `cookiecutter https://github.com/itsbenweeks/template-mit-demo.git --checkout cookie-cutter`
```
Traceback (most recent call last):
  File "/Users/benweeks/code/envs/templater/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.9.1', 'console_scripts', 'cookiecutter')()
  File "/Users/benweeks/code/envs/templater/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Users/benweeks/code/envs/templater/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Users/benweeks/code/envs/templater/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/benweeks/code/envs/templater/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Users/benweeks/code/envs/templater/src/cookiecutter/cookiecutter/cli.py", line 70, in main
    cookiecutter(template, checkout, no_input)
  File "/Users/benweeks/code/envs/templater/src/cookiecutter/cookiecutter/main.py", line 102, in cookiecutter
    context=context
  File "/Users/benweeks/code/envs/templater/src/cookiecutter/cookiecutter/generate.py", line 204, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/Users/benweeks/code/envs/templater/src/cookiecutter/cookiecutter/generate.py", line 114, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/Users/benweeks/code/envs/templater/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/benweeks/code/envs/templater/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/benweeks/code/envs/templater/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/benweeks/code/envs/templater/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/Users/benweeks/code/envs/templater/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 31, in template
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
  File "./problem/Drag_and_drop_problem_created_via_latex2dnd.xml", line 31
    \newcommand\DDB[2]{\DDbox{#1}{6ex}{4ex}{#2}}
```

**Comment by itsbenweeks** [comment]
This was addressed by escaping the latex in this template.
